### ISSUE TITLE
Failure when executing pydebrid.

### ISSUE THREAD

**Issue by plato79** [davidderus/pydebrid#8]
Hi,

I installed pydebrid via pip on FreeBSD. When running though it crashed without giving any output other than this:

```
Traceback (most recent call last):
  File "/usr/local/bin/pydebrid", line 11, in <module>
    load_entry_point('pydebrid==1.0.9', 'console_scripts', 'pydebrid')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2305, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/pydebrid/main.py", line 12, in <module>
    from core import Alldebrid, PydConfig, URI, Downloader, Subtitle
  File "/usr/local/lib/python2.7/site-packages/pydebrid/core/__init__.py", line 5, in <module>
    from subtitle import Subtitle
  File "/usr/local/lib/python2.7/site-packages/pydebrid/core/subtitle.py", line 4, in <module>
    import subliminal
  File "/usr/local/lib/python2.7/site-packages/subliminal/__init__.py", line 10, in <module>
    from .api import (ProviderPool, check_video, provider_manager, download_best_subtitles, download_subtitles,
  File "/usr/local/lib/python2.7/site-packages/subliminal/api.py", line 13, in <module>
    from .subtitle import compute_score, get_subtitle_path
  File "/usr/local/lib/python2.7/site-packages/subliminal/subtitle.py", line 7, in <module>
    from guessit.matchtree import MatchTree
  File "/usr/local/lib/python2.7/site-packages/guessit/__init__.py", line 99, in <module>
    from guessit.plugins import transformers
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 222, in <module>
    reload()
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 220, in reload
    reload_options(all_transformers())
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 179, in all_transformers
    return _extensions.objects()
  File "/usr/local/lib/python2.7/site-packages/guessit/plugins/transformers.py", line 111, in objects
    return self.map(self._get_obj)
  File "/usr/local/lib/python2.7/site-packages/stevedore/extension.py", line 261, in map
    raise NoMatches('No %s extensions found' % self.namespace)
stevedore.exception.NoMatches: No guessit.transformer extensions found

```

I also installed on OSX ( which is FreeBSD based ) and ran it without any problems. What could be the problem?

**Comment by FrankenLab** [comment]
Plato79,  It looks like you're missing the 'guessit' library. See if this helps:
pip install guessit==1.03

**Comment by plato79** [comment]
But it's already installed:

```
$ pip show guessit
Name: guessit
Version: 1.0.3
Summary: GuessIt - a library for guessing information from video filenames.
Home-page: http://guessit.readthedocs.org/
Author: Nicolas Wack
Author-email: wackou@gmail.com
License: LGPLv3
Location: /usr/local/lib/python2.7/site-packages
Requires: babelfish, stevedore, requests, python-dateutil
```

**Comment by FrankenLab** [comment]
After a little more research, it looks like an issue with Stevedore, for details see this post:
[https://github.com/mdhiggins/sickbeard_mp4_automator/issues/643](url)

Try:
pip uninstall stevedore
pip install stevedore==1.19.1

**Comment by davidderus** [comment]
Hi @plato79,
I agree with @ProtoSD, try the fix documented [here](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/643) and get back to us if it does not work.
Otherwise feel free to close the issue.

**Comment by plato79** [comment]
Thanks, it worked like a charm.
